// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxUfaD6TT_PsFMaCz3x3DoMzvDBG6-tjg',
    appId: '1:959608072293:web:27b9158cf80c97e4f07e8c',
    messagingSenderId: '959608072293',
    projectId: 'todo-list-be87b',
    authDomain: 'todo-list-be87b.firebaseapp.com',
    storageBucket: 'todo-list-be87b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNQI_66Mfxjx7u7q4m8eHJOw-m7lHP7Y',
    appId: '1:959608072293:android:24f0a1996e121a5af07e8c',
    messagingSenderId: '959608072293',
    projectId: 'todo-list-be87b',
    storageBucket: 'todo-list-be87b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtdTe6lKDD8ptvOH_QGW5g38S0dwOWmI',
    appId: '1:959608072293:ios:420a53341d909065f07e8c',
    messagingSenderId: '959608072293',
    projectId: 'todo-list-be87b',
    storageBucket: 'todo-list-be87b.firebasestorage.app',
    iosBundleId: 'com.domain.planit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAtdTe6lKDD8ptvOH_QGW5g38S0dwOWmI',
    appId: '1:959608072293:ios:420a53341d909065f07e8c',
    messagingSenderId: '959608072293',
    projectId: 'todo-list-be87b',
    storageBucket: 'todo-list-be87b.firebasestorage.app',
    iosBundleId: 'com.domain.planit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxUfaD6TT_PsFMaCz3x3DoMzvDBG6-tjg',
    appId: '1:959608072293:web:52a9d8d79e8140c6f07e8c',
    messagingSenderId: '959608072293',
    projectId: 'todo-list-be87b',
    authDomain: 'todo-list-be87b.firebaseapp.com',
    storageBucket: 'todo-list-be87b.firebasestorage.app',
  );
}
